chat/urls.py
from django.urls import path
from . import views


app_name = "chat"

urlpatterns = [
    # View chat padrão
    path('room/',
         views.ChatView.as_view(),
         name="chat"),

    # View AJAX que carrega o chat da conversa
    path('room/ajax/friend-chat/',
         views.ChatFriendAjax.as_view(),
         name="html_chat_ajax"),

    # View que cria as mensagens
    path('room/ajax/create-message/',
         views.CreateMessageAjax.as_view(),
         name="chat_save_message_ajax")
]

chat_server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('chat/', include('chat.urls', namespace="chat")),
    path('social/', include('social.urls', namespace="social")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models

from django.contrib.auth.models import User

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from authentication.models import Friend


# Create your models here.
class Message(models.Model):
    """
    O model que salva as mensagens enviadas no chat
    """
    owner = models.ForeignKey(
                    User, on_delete=models.CASCADE, blank=True, null=True)
    created = models.DateTimeField(auto_now=True)
    # Mesagens
    friend_model = models.ForeignKey(
        Friend,
        on_delete=models.CASCADE,
        related_name="chat_messages",
        null=True,
        blank=True,
    )

    target_ct = models.ForeignKey(
        ContentType,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='target_obj',
    )
    target_id = models.PositiveIntegerField(
                    null=True, blank=True, db_index=True)
    target = GenericForeignKey('target_ct', 'target_id')

    def get_message_content(self):
        """
        Metodo que retornará o conteudo da mensagem
        """
        model = self.target_ct.model_class()  # O model que controla o conteudo
        object = model.objects.get(id=self.target_id)

        return object.content


class MessageTextType(models.Model):
    content = models.TextField()


class MessageImageType(models.Model):
    content = models.ImageField(upload_to="media/%Y/%m/%d/")

chat/forms.py
from django import forms
from .models import MessageImageType


class MessageImageForm(forms.ModelForm):
    class Meta:
        model = MessageImageType
        fields = ['content']
        labels = {'content': ''}
        widgets = {'content': forms.FileInput({'class': 'image-send-button'})}

    def clean_content(self, *args, **kwargs):
        image = self.cleaned_data.get('content')

        return image

chat/views.py
from django.views.generic.base import TemplateView, View

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType

from django.http import Http404, HttpResponseForbidden, JsonResponse

from django.shortcuts import get_object_or_404
from django.shortcuts import render

from authentication.models import Friend
from .models import MessageTextType, Message
from .forms import MessageImageForm


# Create your views here.
class AjaxRequiredMixin(View):
    def dispatch(self, request, *args, **kwargs):
        # Salva na váriavel se a requisição é do tipo AJAX
        is_ajax = self.request.headers.get(
                        'x-requested-with') == 'XMLHttpRequest'

        # Se não for, entrega uma página 404
        if not is_ajax:
            return Http404()

        return super().dispatch(request, *args, **kwargs)


class ChatView(LoginRequiredMixin, TemplateView, View):
    """
    Essa view é o chat default, sem estar com nenhum usuário
    """
    template_name = "chat/room/room.html"

    def get(self, request):
        # Todos os amigos
        self.all_friends = request.user.profile.friends.all()

        # Todas as amizades que foram aceitas
        self.all_accepted_friends = self.all_friends.filter(accept=True)

        context = {
            'all_accepted_friends': self.all_accepted_friends,
        }

        return self.render_to_response(context)


class ChatFriendAjax(AjaxRequiredMixin, View):
    """
    Essa view carrega o chat de forma assíncrona com ajax.
    """
    def post(self, request, *args, **kwargs):
        context = {}

        image_form = MessageImageForm()

        friend_id = self.request.POST.get('friend_id')
        friend_object = get_object_or_404(Friend, id=friend_id)

        # Retorna o "user_one" ou "user_two" do modelo Friend
        friend = friend_object.get_friend(self.request.user)

        # Verifica se a amizade existe, senão bloqueia a View
        if friend is None:
            return HttpResponseForbidden()

        # Todas as mensagens salvas para carrega-las no Chat
        messages = friend_object.chat_messages.all()

        context.update({
            'messages': messages,
            'friend': friend,
            'friend_object': friend_object,
            'image_form': image_form,
        })

        return render(request, "chat/ajax_html/_friend_chat.html", context)


class CreateMessageAjax(AjaxRequiredMixin, View):
    """
    Essa view salva as mensagens no banco de dados
    """
    def post(self, request, *args, **kwargs):
        friend_model_id = self.request.POST.get('friend_model_id')
        self.user = self.request.user
        self.type = self.request.POST.get('type')
        self.message = self.request.POST.get('message')

        # verifica que tipo de mensagem é (Texto, Imagem, Video, Arquivo)
        match self.type:
            case "text":
                self.create_text_message(friend_model_id)
            case _:
                ...  # TODO: Criar envio de imagens

        return JsonResponse({'status': "OK"})

    def create_text_message(self, friend_model_id, *args, **kwargs):
        """
        Cria o objeto Message
        """
        friend_object = Friend.objects.get(id=friend_model_id)

        content = MessageTextType.objects.create(content=self.message)
        target_ct = ContentType.objects.get_for_model(MessageTextType)
        target_id = content.id

        Message.objects.create(
            owner=self.user,
            friend_model=friend_object,
            target_ct=target_ct,
            target_id=target_id,
        )

chat/templates/chat/js_html/chatSocket.html
{% load static %}

<script>

const Main = {
  // Função que inicia a classe
  init: function() {
    this.ajaxCsrfToken();
    this.casheSelectors();
    this.bindEvents();
  },

  // A seleção das tags HTML que serão usadas nos métodos
  casheSelectors: function() {
    this.$sendMessageForm = document.querySelector('.div-send-message-control')

    // Selecionando o HTML do chat
    this.$chatMessage = document.querySelector('.chat-messages')

    // O input
    this.$inputMessage = document.querySelector('.send-message')

    // Ul que fica a lista de amigos
    this.$friendsList = document.querySelectorAll('.friends-list')
  
    // O HTML do chat completo
    this.$chatDisplay = document.getElementById('chat_display')

    this.$imageButton = document.querySelector('i.fas.fa-image.fa-3x')

  },

  // Criação do CSRF Token para a requisição AJAX
  ajaxCsrfToken: function() {
    // Cria uma validação de CSRF para metodos posts
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
      // Esses metodos não exigem proteção contra CSRF
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
      beforeSend: (xhr, settings) => {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken)
        }
      }
    });
  },

  // Eventos javascript
  bindEvents: function() {
    const self = this

    this.$friendsList.forEach(function(item, index) {
      // O index 0 é a <ul>, por isso não a ínclui
      if (index !== 0) {
        item.addEventListener(
          'click', self.Events.friendsList_click_ajax.bind(self))
      }
    });

    if (this.$inputMessage) {
      this.$inputMessage.onkeypress = self.Events.inputText_keypress.bind(self)
    }

    if (this.$imageButton) {
      console.log(this.$imageButton)
      this.$imageButton.onclick = function(e) {
        console.log('teste')
      }
    }

  },

  // Objeto que controla a conexão com o WebSocket
  WebSocket: {
    // Detecta se o site está usando HTTPS e faz a modificação na url
    detectSecureUrl: function() {
      this.base_url = "ws";
      if (document.location.protocol === "https:") {
        this.base_url += "s";
      }
      this.base_url += `://${window.location.host}/`; // ws/chat/room/${id}/
    },

    connect: function(friend_model_id) {
      this.detectSecureUrl();
      // Selecionando o HTML do chat
      this.$chatMessage = document.querySelector('.chat-messages')

      // URL do WebSocket
      let url = `${this.base_url}ws/chat/room/${friend_model_id}/`

      console.log(`WebSocket connected: ${url}`)

      const chatSocket = new WebSocket(url)

      // Evento de message do WebSocket
      chatSocket.onmessage = this.receiveChatMessage

      chatSocket.onclose = function(e) {
        console.log(`WebSocket: ${chatSocket.url} is closed`);
      }

      return chatSocket
    },
    
    // Recebe as mensagens do server e a coloca no HTML do chat
    receiveChatMessage: function(datas) {
      // O json que veio do server
      let data = JSON.parse(datas.data);
      // a mensagem digitada pelo usuário
      let message = document.createTextNode(data.message);

      let isMe = data.user !== '{{ request.user }}';

      if (!this.$chatMessage) {
         // Selecionando o HTML do chat se não existir
        this.$chatMessage = document.querySelector('.chat-messages');
      }

      if (isMe) {
        // Mensagem do User atual
        this.$chatMessage.innerHTML += `
          <div class="d-flex justify-content-start mb-4">
            <div class="msg_cotainer">
              <p>
                ${message.textContent}
              </p>
              <span class="msg_time">Now</span>
            </div>
          </div>
        `
      } else {
        // Mensagem do Outro User
        this.$chatMessage.innerHTML += `
          <div class="d-flex justify-content-end mb-4">
            <div class="msg_cotainer_send">
              <p>
                ${message.textContent}
              </p>
              <span class="msg_time_send">Now</span>
            </div>
          </div>
        `
      }

      this.$chatMessage.scrollTop = this.$chatMessage.scrollHeight

    },

  },

  // Objeto que contém os eventos javascript
  Events: {
    /*
    Quando o usuário clicar em um amigo na lista de amigos,
    fará uma requisição AJAX ao servidor e devolverá o chat desse mesmo amigo
    */
    friendsList_click_ajax: function(event) {
      event.preventDefault();
      // ID do model Friend
      let friend_model_id = event.currentTarget.dataset.id;

      // Desconecta do WebSocket atual para conectar a outro
      if (this.chatSocket) {
        // Se o chat atual for o mesmo que o que o usuário quer conectar
        if (this.chatSocket.url.includes(`/${friend_model_id}/`)) {
          return
        }
        this.chatSocket.close()
        delete this.chatSocket
      }

      $.ajax({
        // Faz a requisição AJAX ao servidor
        type: "POST",
        url:  "{% url 'chat:html_chat_ajax' %}",
        data: {
          friend_id: friend_model_id
        }
      }).done((html) => {
        // Conecta no WebSocket
        this.chatSocket = this.WebSocket.connect(friend_model_id)
        // Adiciona o Chat ao HTML atual
        $('#chat_display')[0].innerHTML = html

        // Seleciona as tags HTML novamente
        this.casheSelectors()
        // Adiciona o evento de KeyPress no input das mensagens
        this.$inputMessage.onkeypress = this.Events.inputText_keypress.bind(this)
        
        this.$chatMessage.scrollTop = this.$chatMessage.scrollHeight
      })

    },

    // Evento de click que envia a mensagem do usuário para o WebSocket
    inputText_keypress: function(event) {
      let currentTarget = event.currentTarget

      if (event.key !== "Enter" || currentTarget.value.trim() === '') {
        return
      }
      let message = currentTarget.value;
      let json_message = JSON.stringify({
        'message': message,
      })  // Transforma a mensagem em json

      // Envia para o WebSocket
      this.chatSocket.send(json_message);
      // Remove o conteudo que foi escrito no textarea da mensagem
      currentTarget.value = '';

      friend_object_id = currentTarget.dataset.id

      $.ajax({
        type: "POST",
        url: "{% url 'chat:chat_save_message_ajax' %}",
        data: {
          type: "text",
          message: message,
          friend_model_id: friend_object_id
        }
      });

    },

  }
}


Main.init()

</script>