authentication/urls.py
from django.urls import path
from . import views


app_name = 'authentication'

urlpatterns = [
    path('', views.AuthLoginView.as_view(), name="login"),
    path('register/', views.RegistrationView.as_view(), name="registration"),
    path('logout/', views.logout, name="logout"),
    path('update/', views.EditProfile.as_view(), name="update_account")
]

chat/urls.py
from django.urls import path
from . import views


app_name = "chat"

urlpatterns = [
    # View chat padrão
    path('room/',
         views.ChatView.as_view(),
         name="chat"),

    # View AJAX que carrega o chat da conversa
    path('room/ajax/friend-chat/',
         views.ChatFriendAjax.as_view(),
         name="html_chat_ajax"),

    # View que cria as mensagens
    path('room/ajax/create-message/',
         views.CreateMessageAjax.as_view(),
         name="chat_save_message_ajax")
]

chat_server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('chat/', include('chat.urls', namespace="chat")),
    path('social/', include('social.urls', namespace="social")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from . import views


app_name = "social"

urlpatterns = [
    path('',
         views.UserListView.as_view(),
         name="list_users"),

    path('friend-request/',
         views.CreateSolicitationInviteViewAjax.as_view(),
         name="friend_request"),

    path('friend-request-response/',
         views.ResponseFriendRequestViewAjax.as_view(),
         name="response_friend"),

    path('ajax-count-friend-requests/',
         views.UpdateNewFriendsRequestAjax.as_view(),
         name="count_request_view"),
]

templates/partials/_head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static "base.css" %}">
  <!-- Font Awesome -->
  <link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
  />
  <!-- Google Fonts -->
  <link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
  />
  <!-- MDB -->
  <link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.3.0/mdb.min.css"
  rel="stylesheet"
  />

templates/partials/_navbar.html
{% load static %}
{% load orl_filters %}
{% load thumbnail %}

<header id="navbar-header">
  <div class="main-container nav-content">
    <h1 class="nav-title">Chat<span>Server</span></h1>
    <nav>
      <ul class="center-links">
        <li>
          <a href="{% url "chat:chat" %}">
            Chats
          </a>
          <div class="link-animation"></div>
        </li>
        <li>
          <a href="{% url "social:list_users" %}">
            Social
          </a>
          <div class="link-animation"></div>
        </li>
        <li>
          <a href="">
            Extra
          </a>
          <div class="link-animation"></div>
        </li>
      </ul>
    </nav>
    <div class="user-content">
      <div class="user-nav-links">
        <ul class="navbar-nav flex-row d-none d-md-flex">

          <li class="nav-item dropdown me-3 me-lg-1">
            <a
              class="nav-link dropdown-toggle hidden-arrow"
              href=""
              role="button"
              aria-expanded="false"
            >
              <i class="fas fa-comments fa-2x"></i>
    
              <span class="badge rounded-pill badge-notification bg-danger">6</span><br>
              
            </a>
          </li>
    
          <li class="nav-item dropdown me-3 me-lg-1">
            <a
              class="nav-link dropdown-toggle hidden-arrow"
              href="#"
              id="navbarDropdownMenuLink"
              role="button"
              data-mdb-toggle="dropdown"
              aria-expanded="false"
            >
              <i class="fas fa-users fa-2x"></i>
              {% if friend_requests %}
                <span class="badge rounded-pill badge-notification bg-danger requests">{{ friend_requests.count }}</span><br>
              {% endif %}

            </a>
            <ul
              class="dropdown-menu dropdown-menu-end"
              aria-labelledby="navbarDropdownMenuLink"
            >
              {% for friend_request in friend_requests %}
                <li class="friend_request-content user_{{ friend_request.id }}">
                  {% with friend_request_user=friend_request|get_friend:request.user %}
                    <div class="dropdown-item" href="#">

                      <div class="img-friend-request-content">
                        <img
                          {% if not friend_request_user.profile.photo %}
                            src="{% static 'default_image/no_image2.png' %}"
                          {% else %}
                            src="{% thumbnail friend_request_user.profile.photo 300x300 crop=True %}"
                          {% endif %}
                          class="rounded-circle principal-user-img"
                          alt="Black and White Portrait of a Man"
                          loading="lazy"
                        />
                      </div>
                      <div class="dropdown-item-friend-username">
                        {{ friend_request_user }}
                      </div>
                      
                      <div class="div-accept-or-refuse-friend">
                        <form action="{% url "social:response_friend" %}" method="post">
                          {% csrf_token %}
                          <div>
                            <input type="submit" value="accept" id="input-accept-friend" class="input-friend" name="friend_request_response" data-id="{{ friend_request.id }}">
                          </div>
                          <div>
                            <input type="submit" value="refuse" id="input-refuse-friend" class="input-friend" name="friend_request_response" data-id="{{ friend_request.id }}">
                          </div>
                        </form>
                      </div>

                    </div>
                  {% endwith %}
                </li>
              {% endfor %}

              {% for waiting_friend_request in waiting_friend_requests %}
                <li class="friend_request-content">
                  {% with wait_friend=waiting_friend_request|get_friend:request.user %}
                    <div class="dropdown-item" href="#">

                      <div class="img-friend-request-content">
                        <img
                          {% if not wait_friend.profile.photo %}
                            src="{% static 'default_image/no_image2.png' %}"
                          {% else %}
                            src="{% thumbnail wait_friend.profile.photo 300x300 crop=True %}"
                          {% endif %}
                          class="rounded-circle principal-user-img"
                          alt="Black and White Portrait of a Man"
                          loading="lazy"
                        />
                      </div>
                      <div class="dropdown-item-friend-username">
                        {{ wait_friend }}
                      </div>

                      <div class="div-accept-or-refuse-friend">
                        <div>
                          <input type="submit" value="Aguardando resposta" id="input-wait-friend" class="input-friend">
                        </div>
                      </div>
                    </div>
                  {% endwith %}
                </li>  
              {% endfor %}

            </ul>
          </li>

          <li class="nav-item me-3 me-lg-1">
            <a class="nav-link" href="#">
              <span><i class="fas fa-bell fa-2x"></i></span>
              <span class="badge rounded-pill badge-notification bg-danger">2</span><br>
            </a>
          </li>

        </ul>
      </div>
      <div></div>
      <div class="nav-img-content">
        <a href="{% url 'authentication:update_account' %}">
          {% with user_profile=request.user.profile %}
            <img
              {% if not user_profile.photo %}
                src="{% static 'default_image/no_image2.png' %}"
              {% else %}
                src="{% thumbnail user_profile.photo 50x50 crop=300 %}"
              {% endif %}
              class="rounded-circle principal-user-img"
              alt="Black and White Portrait of a Man"
              loading="lazy"
            />
          {% endwith %}
        </a>
      </div>
    </div>
  </div>
</header>