chat/urls.py
from django.urls import path
from . import views


app_name = "chat"

urlpatterns = [
    # View chat padrão
    path('room/',
         views.ChatView.as_view(),
         name="chat"),

    # View AJAX que carrega o chat da conversa
    path('room/ajax/friend-chat/',
         views.ChatFriendAjax.as_view(),
         name="html_chat_ajax"),

    # View que cria as mensagens
    path('room/ajax/create-message/',
         views.CreateMessageAjax.as_view(),
         name="chat_save_message_ajax")
]

chat_server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('chat/', include('chat.urls', namespace="chat")),
    path('social/', include('social.urls', namespace="social")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from . import views


app_name = "social"

urlpatterns = [
    path('',
         views.UserListView.as_view(),
         name="list_users"),

    path('friend-request/',
         views.CreateSolicitationInviteViewAjax.as_view(),
         name="friend_request"),

    path('friend-request-response/',
         views.ResponseFriendRequestViewAjax.as_view(),
         name="response_friend"),

    path('ajax-count-friend-requests/',
         views.UpdateNewFriendsRequestAjax.as_view(),
         name="count_request_view"),
]

social/models.py
from django.db import models

# Create your models here.

social/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404

from django.contrib.auth.models import User

from django.views.generic.list import ListView
from django.views.generic.base import TemplateResponseMixin, View

from django.contrib.auth.mixins import LoginRequiredMixin

from authentication.models import Friend
from chat.views import AjaxRequiredMixin


class UserListView(LoginRequiredMixin, ListView):
    template_name = "social/users/list.html"
    model = User
    context_object_name = "users"

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        # Exclui o usuário que enviou a solicitação e o próprio
        qs = qs.exclude(id=self.request.user.id) \
               .exclude(profile__friends__user_one=self.request.user) \
               .exclude(profile__friends__user_two=self.request.user)

        return qs


class CreateSolicitationInviteViewAjax(
            LoginRequiredMixin, TemplateResponseMixin, View):
    """
    Classe que envia a solicitação de amizade
    """
    def post(self, request, *args, **kwargs):
        user = self.request.user
        friend_id = self.request.POST.get('user_id')

        # Seleciona o usuário que receberá a solicitação
        other_user = get_object_or_404(User, id=friend_id)

        friend_already_exists = Friend.objects.filter(
            user_one=user, user_two=other_user).first()
        if friend_already_exists:
            friend_already_exists.delete()
            return JsonResponse({'status': 'ok'})

        # Cria um objeto Friend onde user_one é quem enviou a solicitação
        friend = Friend.objects.create(
            user_one=user,
            user_two=other_user,
        )

        #  Adiciona o objeto Friend aos usuários que se conectarão,
        #  independente se o pedido foi aceito ou não
        other_user.profile.friends.add(friend)
        user.profile.friends.add(friend)

        return JsonResponse({'status': 'ok'})


class ResponseFriendRequestViewAjax(
        AjaxRequiredMixin, TemplateResponseMixin, View):
    """
    Classe que, quando o usuário clicar em aceitar um pedido de amizade ou
    recusar, fará o tratamento nescessário e fará uma ligação entre os dois
    usuários
    """
    def post(self, request, *args, **kwargs):
        model_friend_id = self.request.POST.get("friend_model_id")

        # Recebe a resposta do pedido como "accept" ou "refuse"
        response = self.request.POST.get('friend_response')

        friend = get_object_or_404(Friend, id=model_friend_id)

        if response == "accept":
            friend.accept = True  # Aceita o pedido
            friend.save()
        elif response == "refuse":
            friend.delete()  # Recusa o pedido

        return JsonResponse({'status': 'OK'})


class UpdateNewFriendsRequestAjax(AjaxRequiredMixin, View):
    """
    Atualiza o contador de requisições de amizades na Navbar
    """
    def get(self, request, *args, **kwargs):
        user = self.request.user

        if not user.is_authenticated:
            return None

        # Os usuários que ainda não foram aceitos ou recusados pelo user atual
        user_friends = user.profile.friends.all() \
                                   .filter(accept=None) \
                                   .exclude(user_one=user)

        return JsonResponse({'user_friends_count': user_friends.count()})

social/templates/social/users/list.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}


{% block head %}
  <link rel="stylesheet" href="{% static "social/css/social.css" %}">

  <title>Chat | Social</title>
{% endblock %}

{% block content %}


  <main class="main-container social">

    <div class="user-profile-details">
      <div class="perfil-image-content">
        <img
          {% with request.user.profile as user_profile %}
            {% if not user_profile.photo %}
              src="{% static 'default_image/no_image2.png' %}"
            {% else %}
              src="{% thumbnail user_profile.photo 300x300 crop=True %}"
            {% endif %}
          {% endwith %}
          alt="" class="rounded-circle"
        >
      </div>
      <div class="div-separator"></div>
      <div class="user-info">
        <div class="info">
          <span class="default-text">Nome de usuário:</span> <span>{{ request.user.username }}</span>
        </div>
      </div>
      <div class="div-separator"></div>
      <div class="about-me">
        <span class="default-text-inline">Sobre mim:</span> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Illum aliquam pariatur ipsum dolore? Accusantium cupiditate ea nihil qui? Voluptates esse cum corporis, accusantium nisi repudiandae saepe quam officiis magnam consectetur?

      </div>
    </div>

    <div class="content-users-list">
      <div>

      </div>
      <div class="add-friends-content">
        <ul>

          {% for user in users %}
            <li class="add-user">
              <div class="user-image-content">
                <img
                  {% if not user.profile.photo %}
                    src="{% static "default_image/no_image2.png" %}"
                  {% else %}
                    src="{% thumbnail user.profile.photo 300x300 crop=True %}"
                  {% endif %}
                  alt=""
                  class="rounded-circle"
                >
              </div>
              <div class="friend-user-info">
                <div>
                  <span class="username">{{ user }}</span>
                </div>
              </div>
              <div class="form-friend-request">
                <form action="{% url "social:friend_request" %}" method="post" class="form-add-friend">
                  {% csrf_token %}
                  <input type="submit" value="Enviar pedido de amizade" class="input-add-friend" data-id="{{ user.id }}">
                </form>
              </div>
            </li>
          {% endfor %}

        </ul>
      </div>
    </div>
    
  </main>
  
{% endblock content %}

{% block dom_include %}
  {% include "social/html_js/social_js.html" %}
{% endblock %}